### PR TITLE
update codebase to match Replicate guide

### PR DESCRIPTION
**Pull request by zeke**
This updates the codebase to match what users will get when they go through the steps in this guide: https://replicate.com/docs/get-started/nextjs

It also updates the README with real content: https://github.com/replicate/getting-started-nextjs/pull/5/commits/dd997d5c6f9f92af27107eeecd978acd3ee5655c

Followup to https://github.com/replicate/replicate-web/pull/2753

### CODE REVIEW

**Comment by zeke** [comment]
@bfirsh do you know what's up with this License Compliance check? Is this something you installed?

When I tried to view the details of the failing check, I logged in with my GitHub account and I now see this onboarding page:

Screen Shot 2022-12-28 at 11 46 14 AM

**Comment by bfirsh** [comment]
Yeah, just ignore that. I'll figure out how to switch it off.

**Comment by bfirsh** [comment]
I haven't thoroughly reviewed this, but it's presumably a lot more functional than what is currently in the repository. :)

**Comment by kimberleehowley** [comment]
No feedback from my review! This is great. Thank you!

**Pull request merged**
